// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MVM_opcion7_super_mejorada_MVM_opcion7_super_mejorada,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.512000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=6769,HLS_SYN_LUT=9084,HLS_VERSION=2020_2}" *)

module MVM_opcion7_super_mejorada (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] input1;
wire   [63:0] input2;
wire   [63:0] output_r;
wire   [31:0] MM;
wire   [31:0] NN;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem_AWREADY;
wire    gmem_WREADY;
wire    gmem_ARREADY;
wire    gmem_RVALID;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
wire    producer3_U0_ap_start;
wire    producer3_U0_start_full_n;
wire    producer3_U0_ap_done;
wire    producer3_U0_ap_continue;
wire    producer3_U0_ap_idle;
wire    producer3_U0_ap_ready;
wire    producer3_U0_start_out;
wire    producer3_U0_start_write;
wire   [31:0] producer3_U0_aa_din;
wire    producer3_U0_aa_write;
wire   [31:0] producer3_U0_bb1_din;
wire    producer3_U0_bb1_write;
wire    producer3_U0_m_axi_gmem_AWVALID;
wire   [63:0] producer3_U0_m_axi_gmem_AWADDR;
wire   [0:0] producer3_U0_m_axi_gmem_AWID;
wire   [31:0] producer3_U0_m_axi_gmem_AWLEN;
wire   [2:0] producer3_U0_m_axi_gmem_AWSIZE;
wire   [1:0] producer3_U0_m_axi_gmem_AWBURST;
wire   [1:0] producer3_U0_m_axi_gmem_AWLOCK;
wire   [3:0] producer3_U0_m_axi_gmem_AWCACHE;
wire   [2:0] producer3_U0_m_axi_gmem_AWPROT;
wire   [3:0] producer3_U0_m_axi_gmem_AWQOS;
wire   [3:0] producer3_U0_m_axi_gmem_AWREGION;
wire   [0:0] producer3_U0_m_axi_gmem_AWUSER;
wire    producer3_U0_m_axi_gmem_WVALID;
wire   [31:0] producer3_U0_m_axi_gmem_WDATA;
wire   [3:0] producer3_U0_m_axi_gmem_WSTRB;
wire    producer3_U0_m_axi_gmem_WLAST;
wire   [0:0] producer3_U0_m_axi_gmem_WID;
wire   [0:0] producer3_U0_m_axi_gmem_WUSER;
wire    producer3_U0_m_axi_gmem_ARVALID;
wire   [63:0] producer3_U0_m_axi_gmem_ARADDR;
wire   [0:0] producer3_U0_m_axi_gmem_ARID;
wire   [31:0] producer3_U0_m_axi_gmem_ARLEN;
wire   [2:0] producer3_U0_m_axi_gmem_ARSIZE;
wire   [1:0] producer3_U0_m_axi_gmem_ARBURST;
wire   [1:0] producer3_U0_m_axi_gmem_ARLOCK;
wire   [3:0] producer3_U0_m_axi_gmem_ARCACHE;
wire   [2:0] producer3_U0_m_axi_gmem_ARPROT;
wire   [3:0] producer3_U0_m_axi_gmem_ARQOS;
wire   [3:0] producer3_U0_m_axi_gmem_ARREGION;
wire   [0:0] producer3_U0_m_axi_gmem_ARUSER;
wire    producer3_U0_m_axi_gmem_RREADY;
wire    producer3_U0_m_axi_gmem_BREADY;
wire   [31:0] producer3_U0_DESTINO_out_din;
wire    producer3_U0_DESTINO_out_write;
wire   [31:0] producer3_U0_ORIGEN_out_din;
wire    producer3_U0_ORIGEN_out_write;
wire   [63:0] producer3_U0_output_out_din;
wire    producer3_U0_output_out_write;
wire    layer1_U0_ap_start;
wire    layer1_U0_ap_done;
wire    layer1_U0_ap_continue;
wire    layer1_U0_ap_idle;
wire    layer1_U0_ap_ready;
wire    layer1_U0_aa_read;
wire    layer1_U0_bb1_read;
wire   [31:0] layer1_U0_ss_din;
wire    layer1_U0_ss_write;
wire    layer1_U0_DESTINO_read;
wire    layer1_U0_ORIGEN_read;
wire   [31:0] layer1_U0_DESTINO_out_din;
wire    layer1_U0_DESTINO_out_write;
wire    consumer_U0_ap_start;
wire    consumer_U0_ap_done;
wire    consumer_U0_ap_continue;
wire    consumer_U0_ap_idle;
wire    consumer_U0_ap_ready;
wire    consumer_U0_ss_read;
wire    consumer_U0_m_axi_gmem_AWVALID;
wire   [63:0] consumer_U0_m_axi_gmem_AWADDR;
wire   [0:0] consumer_U0_m_axi_gmem_AWID;
wire   [31:0] consumer_U0_m_axi_gmem_AWLEN;
wire   [2:0] consumer_U0_m_axi_gmem_AWSIZE;
wire   [1:0] consumer_U0_m_axi_gmem_AWBURST;
wire   [1:0] consumer_U0_m_axi_gmem_AWLOCK;
wire   [3:0] consumer_U0_m_axi_gmem_AWCACHE;
wire   [2:0] consumer_U0_m_axi_gmem_AWPROT;
wire   [3:0] consumer_U0_m_axi_gmem_AWQOS;
wire   [3:0] consumer_U0_m_axi_gmem_AWREGION;
wire   [0:0] consumer_U0_m_axi_gmem_AWUSER;
wire    consumer_U0_m_axi_gmem_WVALID;
wire   [31:0] consumer_U0_m_axi_gmem_WDATA;
wire   [3:0] consumer_U0_m_axi_gmem_WSTRB;
wire    consumer_U0_m_axi_gmem_WLAST;
wire   [0:0] consumer_U0_m_axi_gmem_WID;
wire   [0:0] consumer_U0_m_axi_gmem_WUSER;
wire    consumer_U0_m_axi_gmem_ARVALID;
wire   [63:0] consumer_U0_m_axi_gmem_ARADDR;
wire   [0:0] consumer_U0_m_axi_gmem_ARID;
wire   [31:0] consumer_U0_m_axi_gmem_ARLEN;
wire   [2:0] consumer_U0_m_axi_gmem_ARSIZE;
wire   [1:0] consumer_U0_m_axi_gmem_ARBURST;
wire   [1:0] consumer_U0_m_axi_gmem_ARLOCK;
wire   [3:0] consumer_U0_m_axi_gmem_ARCACHE;
wire   [2:0] consumer_U0_m_axi_gmem_ARPROT;
wire   [3:0] consumer_U0_m_axi_gmem_ARQOS;
wire   [3:0] consumer_U0_m_axi_gmem_ARREGION;
wire   [0:0] consumer_U0_m_axi_gmem_ARUSER;
wire    consumer_U0_m_axi_gmem_RREADY;
wire    consumer_U0_m_axi_gmem_BREADY;
wire    consumer_U0_activacion_read;
wire    consumer_U0_DESTINO_read;
wire    ap_sync_continue;
wire    a_full_n;
wire   [31:0] a_dout;
wire    a_empty_n;
wire    b1_full_n;
wire   [31:0] b1_dout;
wire    b1_empty_n;
wire    MM_c_full_n;
wire   [31:0] MM_c_dout;
wire    MM_c_empty_n;
wire    NN_c_full_n;
wire   [31:0] NN_c_dout;
wire    NN_c_empty_n;
wire    output_c_full_n;
wire   [63:0] output_c_dout;
wire    output_c_empty_n;
wire    layer1_layer2_full_n;
wire   [31:0] layer1_layer2_dout;
wire    layer1_layer2_empty_n;
wire    MM_c9_full_n;
wire   [31:0] MM_c9_dout;
wire    MM_c9_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_layer1_U0_din;
wire    start_for_layer1_U0_full_n;
wire   [0:0] start_for_layer1_U0_dout;
wire    start_for_layer1_U0_empty_n;
wire   [0:0] start_for_consumer_U0_din;
wire    start_for_consumer_U0_full_n;
wire   [0:0] start_for_consumer_U0_dout;
wire    start_for_consumer_U0_empty_n;
wire    layer1_U0_start_full_n;
wire    layer1_U0_start_write;
wire    consumer_U0_start_full_n;
wire    consumer_U0_start_write;

MVM_opcion7_super_mejorada_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input1(input1),
    .input2(input2),
    .output_r(output_r),
    .MM(MM),
    .NN(NN),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

MVM_opcion7_super_mejorada_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(producer3_U0_m_axi_gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(producer3_U0_m_axi_gmem_ARADDR),
    .I_ARID(producer3_U0_m_axi_gmem_ARID),
    .I_ARLEN(producer3_U0_m_axi_gmem_ARLEN),
    .I_ARSIZE(producer3_U0_m_axi_gmem_ARSIZE),
    .I_ARLOCK(producer3_U0_m_axi_gmem_ARLOCK),
    .I_ARCACHE(producer3_U0_m_axi_gmem_ARCACHE),
    .I_ARQOS(producer3_U0_m_axi_gmem_ARQOS),
    .I_ARPROT(producer3_U0_m_axi_gmem_ARPROT),
    .I_ARUSER(producer3_U0_m_axi_gmem_ARUSER),
    .I_ARBURST(producer3_U0_m_axi_gmem_ARBURST),
    .I_ARREGION(producer3_U0_m_axi_gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(producer3_U0_m_axi_gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(consumer_U0_m_axi_gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(consumer_U0_m_axi_gmem_AWADDR),
    .I_AWID(consumer_U0_m_axi_gmem_AWID),
    .I_AWLEN(consumer_U0_m_axi_gmem_AWLEN),
    .I_AWSIZE(consumer_U0_m_axi_gmem_AWSIZE),
    .I_AWLOCK(consumer_U0_m_axi_gmem_AWLOCK),
    .I_AWCACHE(consumer_U0_m_axi_gmem_AWCACHE),
    .I_AWQOS(consumer_U0_m_axi_gmem_AWQOS),
    .I_AWPROT(consumer_U0_m_axi_gmem_AWPROT),
    .I_AWUSER(consumer_U0_m_axi_gmem_AWUSER),
    .I_AWBURST(consumer_U0_m_axi_gmem_AWBURST),
    .I_AWREGION(consumer_U0_m_axi_gmem_AWREGION),
    .I_WVALID(consumer_U0_m_axi_gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(consumer_U0_m_axi_gmem_WDATA),
    .I_WID(consumer_U0_m_axi_gmem_WID),
    .I_WUSER(consumer_U0_m_axi_gmem_WUSER),
    .I_WLAST(consumer_U0_m_axi_gmem_WLAST),
    .I_WSTRB(consumer_U0_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(consumer_U0_m_axi_gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

MVM_opcion7_super_mejorada_producer3 producer3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(producer3_U0_ap_start),
    .start_full_n(producer3_U0_start_full_n),
    .ap_done(producer3_U0_ap_done),
    .ap_continue(producer3_U0_ap_continue),
    .ap_idle(producer3_U0_ap_idle),
    .ap_ready(producer3_U0_ap_ready),
    .start_out(producer3_U0_start_out),
    .start_write(producer3_U0_start_write),
    .aa_din(producer3_U0_aa_din),
    .aa_full_n(a_full_n),
    .aa_write(producer3_U0_aa_write),
    .bb1_din(producer3_U0_bb1_din),
    .bb1_full_n(b1_full_n),
    .bb1_write(producer3_U0_bb1_write),
    .m_axi_gmem_AWVALID(producer3_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(producer3_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(producer3_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(producer3_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(producer3_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(producer3_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(producer3_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(producer3_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(producer3_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(producer3_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(producer3_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(producer3_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(producer3_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(producer3_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(producer3_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(producer3_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(producer3_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(producer3_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(producer3_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(producer3_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(producer3_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(producer3_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(producer3_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(producer3_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(producer3_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(producer3_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(producer3_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(producer3_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(producer3_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(producer3_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(producer3_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(producer3_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .activacion(input1),
    .weight(input2),
    .DESTINO(MM),
    .ORIGEN(NN),
    .output_r(output_r),
    .DESTINO_out_din(producer3_U0_DESTINO_out_din),
    .DESTINO_out_full_n(MM_c_full_n),
    .DESTINO_out_write(producer3_U0_DESTINO_out_write),
    .ORIGEN_out_din(producer3_U0_ORIGEN_out_din),
    .ORIGEN_out_full_n(NN_c_full_n),
    .ORIGEN_out_write(producer3_U0_ORIGEN_out_write),
    .output_out_din(producer3_U0_output_out_din),
    .output_out_full_n(output_c_full_n),
    .output_out_write(producer3_U0_output_out_write)
);

MVM_opcion7_super_mejorada_layer1 layer1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(layer1_U0_ap_start),
    .ap_done(layer1_U0_ap_done),
    .ap_continue(layer1_U0_ap_continue),
    .ap_idle(layer1_U0_ap_idle),
    .ap_ready(layer1_U0_ap_ready),
    .aa_dout(a_dout),
    .aa_empty_n(a_empty_n),
    .aa_read(layer1_U0_aa_read),
    .bb1_dout(b1_dout),
    .bb1_empty_n(b1_empty_n),
    .bb1_read(layer1_U0_bb1_read),
    .ss_din(layer1_U0_ss_din),
    .ss_full_n(layer1_layer2_full_n),
    .ss_write(layer1_U0_ss_write),
    .DESTINO_dout(MM_c_dout),
    .DESTINO_empty_n(MM_c_empty_n),
    .DESTINO_read(layer1_U0_DESTINO_read),
    .ORIGEN_dout(NN_c_dout),
    .ORIGEN_empty_n(NN_c_empty_n),
    .ORIGEN_read(layer1_U0_ORIGEN_read),
    .DESTINO_out_din(layer1_U0_DESTINO_out_din),
    .DESTINO_out_full_n(MM_c9_full_n),
    .DESTINO_out_write(layer1_U0_DESTINO_out_write)
);

MVM_opcion7_super_mejorada_consumer consumer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(consumer_U0_ap_start),
    .ap_done(consumer_U0_ap_done),
    .ap_continue(consumer_U0_ap_continue),
    .ap_idle(consumer_U0_ap_idle),
    .ap_ready(consumer_U0_ap_ready),
    .ss_dout(layer1_layer2_dout),
    .ss_empty_n(layer1_layer2_empty_n),
    .ss_read(consumer_U0_ss_read),
    .m_axi_gmem_AWVALID(consumer_U0_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(consumer_U0_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(consumer_U0_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(consumer_U0_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(consumer_U0_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(consumer_U0_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(consumer_U0_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(consumer_U0_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(consumer_U0_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(consumer_U0_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(consumer_U0_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(consumer_U0_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(consumer_U0_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(consumer_U0_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(consumer_U0_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(consumer_U0_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(consumer_U0_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(consumer_U0_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(consumer_U0_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(consumer_U0_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(consumer_U0_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(consumer_U0_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(consumer_U0_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(consumer_U0_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(consumer_U0_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(consumer_U0_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(consumer_U0_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(consumer_U0_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(consumer_U0_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(consumer_U0_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(consumer_U0_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(consumer_U0_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(gmem_BRESP),
    .m_axi_gmem_BID(gmem_BID),
    .m_axi_gmem_BUSER(gmem_BUSER),
    .activacion_dout(output_c_dout),
    .activacion_empty_n(output_c_empty_n),
    .activacion_read(consumer_U0_activacion_read),
    .DESTINO_dout(MM_c9_dout),
    .DESTINO_empty_n(MM_c9_empty_n),
    .DESTINO_read(consumer_U0_DESTINO_read)
);

MVM_opcion7_super_mejorada_fifo_w32_d2_S a_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(producer3_U0_aa_din),
    .if_full_n(a_full_n),
    .if_write(producer3_U0_aa_write),
    .if_dout(a_dout),
    .if_empty_n(a_empty_n),
    .if_read(layer1_U0_aa_read)
);

MVM_opcion7_super_mejorada_fifo_w32_d2_S b1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(producer3_U0_bb1_din),
    .if_full_n(b1_full_n),
    .if_write(producer3_U0_bb1_write),
    .if_dout(b1_dout),
    .if_empty_n(b1_empty_n),
    .if_read(layer1_U0_bb1_read)
);

MVM_opcion7_super_mejorada_fifo_w32_d2_S MM_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(producer3_U0_DESTINO_out_din),
    .if_full_n(MM_c_full_n),
    .if_write(producer3_U0_DESTINO_out_write),
    .if_dout(MM_c_dout),
    .if_empty_n(MM_c_empty_n),
    .if_read(layer1_U0_DESTINO_read)
);

MVM_opcion7_super_mejorada_fifo_w32_d2_S NN_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(producer3_U0_ORIGEN_out_din),
    .if_full_n(NN_c_full_n),
    .if_write(producer3_U0_ORIGEN_out_write),
    .if_dout(NN_c_dout),
    .if_empty_n(NN_c_empty_n),
    .if_read(layer1_U0_ORIGEN_read)
);

MVM_opcion7_super_mejorada_fifo_w64_d3_S output_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(producer3_U0_output_out_din),
    .if_full_n(output_c_full_n),
    .if_write(producer3_U0_output_out_write),
    .if_dout(output_c_dout),
    .if_empty_n(output_c_empty_n),
    .if_read(consumer_U0_activacion_read)
);

MVM_opcion7_super_mejorada_fifo_w32_d2_S layer1_layer2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(layer1_U0_ss_din),
    .if_full_n(layer1_layer2_full_n),
    .if_write(layer1_U0_ss_write),
    .if_dout(layer1_layer2_dout),
    .if_empty_n(layer1_layer2_empty_n),
    .if_read(consumer_U0_ss_read)
);

MVM_opcion7_super_mejorada_fifo_w32_d2_S MM_c9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(layer1_U0_DESTINO_out_din),
    .if_full_n(MM_c9_full_n),
    .if_write(layer1_U0_DESTINO_out_write),
    .if_dout(MM_c9_dout),
    .if_empty_n(MM_c9_empty_n),
    .if_read(consumer_U0_DESTINO_read)
);

MVM_opcion7_super_mejorada_start_for_layer1_U0 start_for_layer1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_layer1_U0_din),
    .if_full_n(start_for_layer1_U0_full_n),
    .if_write(producer3_U0_start_write),
    .if_dout(start_for_layer1_U0_dout),
    .if_empty_n(start_for_layer1_U0_empty_n),
    .if_read(layer1_U0_ap_ready)
);

MVM_opcion7_super_mejorada_start_for_consumer_U0 start_for_consumer_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_consumer_U0_din),
    .if_full_n(start_for_consumer_U0_full_n),
    .if_write(producer3_U0_start_write),
    .if_dout(start_for_consumer_U0_dout),
    .if_empty_n(start_for_consumer_U0_empty_n),
    .if_read(consumer_U0_ap_ready)
);

assign ap_done = consumer_U0_ap_done;

assign ap_idle = (producer3_U0_ap_idle & layer1_U0_ap_idle & consumer_U0_ap_idle);

assign ap_ready = producer3_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b1;

assign ap_sync_done = consumer_U0_ap_done;

assign ap_sync_ready = producer3_U0_ap_ready;

assign consumer_U0_ap_continue = 1'b1;

assign consumer_U0_ap_start = start_for_consumer_U0_empty_n;

assign consumer_U0_start_full_n = 1'b1;

assign consumer_U0_start_write = 1'b0;

assign layer1_U0_ap_continue = 1'b1;

assign layer1_U0_ap_start = start_for_layer1_U0_empty_n;

assign layer1_U0_start_full_n = 1'b1;

assign layer1_U0_start_write = 1'b0;

assign producer3_U0_ap_continue = 1'b1;

assign producer3_U0_ap_start = ap_start;

assign producer3_U0_start_full_n = (start_for_layer1_U0_full_n & start_for_consumer_U0_full_n);

assign start_for_consumer_U0_din = 1'b1;

assign start_for_layer1_U0_din = 1'b1;

endmodule //MVM_opcion7_super_mejorada
