-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MVM_opcion7_super_mejorada is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of MVM_opcion7_super_mejorada is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "MVM_opcion7_super_mejorada_MVM_opcion7_super_mejorada,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=14.512000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=6769,HLS_SYN_LUT=9084,HLS_VERSION=2020_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_S_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_S_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_ID_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ADDR_WIDTH : INTEGER range 63 downto 0 := 40;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_WSTRB_WIDTH : INTEGER range 63 downto 0 := 4;
    constant C_M_AXI_AWUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_ARUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_WUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_RUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant C_M_AXI_BUSER_WIDTH : INTEGER range 63 downto 0 := 1;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal input1 : STD_LOGIC_VECTOR (63 downto 0);
    signal input2 : STD_LOGIC_VECTOR (63 downto 0);
    signal output_r : STD_LOGIC_VECTOR (63 downto 0);
    signal MM : STD_LOGIC_VECTOR (31 downto 0);
    signal NN : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RLAST : STD_LOGIC;
    signal gmem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_ap_start : STD_LOGIC;
    signal producer3_U0_start_full_n : STD_LOGIC;
    signal producer3_U0_ap_done : STD_LOGIC;
    signal producer3_U0_ap_continue : STD_LOGIC;
    signal producer3_U0_ap_idle : STD_LOGIC;
    signal producer3_U0_ap_ready : STD_LOGIC;
    signal producer3_U0_start_out : STD_LOGIC;
    signal producer3_U0_start_write : STD_LOGIC;
    signal producer3_U0_aa_din : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_aa_write : STD_LOGIC;
    signal producer3_U0_bb1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_bb1_write : STD_LOGIC;
    signal producer3_U0_m_axi_gmem_AWVALID : STD_LOGIC;
    signal producer3_U0_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal producer3_U0_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal producer3_U0_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal producer3_U0_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal producer3_U0_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal producer3_U0_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_m_axi_gmem_WVALID : STD_LOGIC;
    signal producer3_U0_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_WLAST : STD_LOGIC;
    signal producer3_U0_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_m_axi_gmem_ARVALID : STD_LOGIC;
    signal producer3_U0_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal producer3_U0_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal producer3_U0_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal producer3_U0_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal producer3_U0_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal producer3_U0_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal producer3_U0_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal producer3_U0_m_axi_gmem_RREADY : STD_LOGIC;
    signal producer3_U0_m_axi_gmem_BREADY : STD_LOGIC;
    signal producer3_U0_DESTINO_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_DESTINO_out_write : STD_LOGIC;
    signal producer3_U0_ORIGEN_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal producer3_U0_ORIGEN_out_write : STD_LOGIC;
    signal producer3_U0_output_out_din : STD_LOGIC_VECTOR (63 downto 0);
    signal producer3_U0_output_out_write : STD_LOGIC;
    signal layer1_U0_ap_start : STD_LOGIC;
    signal layer1_U0_ap_done : STD_LOGIC;
    signal layer1_U0_ap_continue : STD_LOGIC;
    signal layer1_U0_ap_idle : STD_LOGIC;
    signal layer1_U0_ap_ready : STD_LOGIC;
    signal layer1_U0_aa_read : STD_LOGIC;
    signal layer1_U0_bb1_read : STD_LOGIC;
    signal layer1_U0_ss_din : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_U0_ss_write : STD_LOGIC;
    signal layer1_U0_DESTINO_read : STD_LOGIC;
    signal layer1_U0_ORIGEN_read : STD_LOGIC;
    signal layer1_U0_DESTINO_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_U0_DESTINO_out_write : STD_LOGIC;
    signal consumer_U0_ap_start : STD_LOGIC;
    signal consumer_U0_ap_done : STD_LOGIC;
    signal consumer_U0_ap_continue : STD_LOGIC;
    signal consumer_U0_ap_idle : STD_LOGIC;
    signal consumer_U0_ap_ready : STD_LOGIC;
    signal consumer_U0_ss_read : STD_LOGIC;
    signal consumer_U0_m_axi_gmem_AWVALID : STD_LOGIC;
    signal consumer_U0_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal consumer_U0_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal consumer_U0_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal consumer_U0_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal consumer_U0_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal consumer_U0_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal consumer_U0_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal consumer_U0_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal consumer_U0_m_axi_gmem_WVALID : STD_LOGIC;
    signal consumer_U0_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal consumer_U0_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_WLAST : STD_LOGIC;
    signal consumer_U0_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal consumer_U0_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal consumer_U0_m_axi_gmem_ARVALID : STD_LOGIC;
    signal consumer_U0_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal consumer_U0_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal consumer_U0_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal consumer_U0_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal consumer_U0_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal consumer_U0_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal consumer_U0_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal consumer_U0_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal consumer_U0_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal consumer_U0_m_axi_gmem_RREADY : STD_LOGIC;
    signal consumer_U0_m_axi_gmem_BREADY : STD_LOGIC;
    signal consumer_U0_activacion_read : STD_LOGIC;
    signal consumer_U0_DESTINO_read : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal a_full_n : STD_LOGIC;
    signal a_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal a_empty_n : STD_LOGIC;
    signal b1_full_n : STD_LOGIC;
    signal b1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal b1_empty_n : STD_LOGIC;
    signal MM_c_full_n : STD_LOGIC;
    signal MM_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal MM_c_empty_n : STD_LOGIC;
    signal NN_c_full_n : STD_LOGIC;
    signal NN_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal NN_c_empty_n : STD_LOGIC;
    signal output_c_full_n : STD_LOGIC;
    signal output_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal output_c_empty_n : STD_LOGIC;
    signal layer1_layer2_full_n : STD_LOGIC;
    signal layer1_layer2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal layer1_layer2_empty_n : STD_LOGIC;
    signal MM_c9_full_n : STD_LOGIC;
    signal MM_c9_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal MM_c9_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_layer1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer1_U0_full_n : STD_LOGIC;
    signal start_for_layer1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_layer1_U0_empty_n : STD_LOGIC;
    signal start_for_consumer_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_consumer_U0_full_n : STD_LOGIC;
    signal start_for_consumer_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_consumer_U0_empty_n : STD_LOGIC;
    signal layer1_U0_start_full_n : STD_LOGIC;
    signal layer1_U0_start_write : STD_LOGIC;
    signal consumer_U0_start_full_n : STD_LOGIC;
    signal consumer_U0_start_write : STD_LOGIC;

    component MVM_opcion7_super_mejorada_producer3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        aa_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        aa_full_n : IN STD_LOGIC;
        aa_write : OUT STD_LOGIC;
        bb1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        bb1_full_n : IN STD_LOGIC;
        bb1_write : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        activacion : IN STD_LOGIC_VECTOR (63 downto 0);
        weight : IN STD_LOGIC_VECTOR (63 downto 0);
        DESTINO : IN STD_LOGIC_VECTOR (31 downto 0);
        ORIGEN : IN STD_LOGIC_VECTOR (31 downto 0);
        output_r : IN STD_LOGIC_VECTOR (63 downto 0);
        DESTINO_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        DESTINO_out_full_n : IN STD_LOGIC;
        DESTINO_out_write : OUT STD_LOGIC;
        ORIGEN_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ORIGEN_out_full_n : IN STD_LOGIC;
        ORIGEN_out_write : OUT STD_LOGIC;
        output_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        output_out_full_n : IN STD_LOGIC;
        output_out_write : OUT STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_layer1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        aa_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        aa_empty_n : IN STD_LOGIC;
        aa_read : OUT STD_LOGIC;
        bb1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        bb1_empty_n : IN STD_LOGIC;
        bb1_read : OUT STD_LOGIC;
        ss_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ss_full_n : IN STD_LOGIC;
        ss_write : OUT STD_LOGIC;
        DESTINO_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        DESTINO_empty_n : IN STD_LOGIC;
        DESTINO_read : OUT STD_LOGIC;
        ORIGEN_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ORIGEN_empty_n : IN STD_LOGIC;
        ORIGEN_read : OUT STD_LOGIC;
        DESTINO_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        DESTINO_out_full_n : IN STD_LOGIC;
        DESTINO_out_write : OUT STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_consumer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ss_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ss_empty_n : IN STD_LOGIC;
        ss_read : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        activacion_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        activacion_empty_n : IN STD_LOGIC;
        activacion_read : OUT STD_LOGIC;
        DESTINO_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        DESTINO_empty_n : IN STD_LOGIC;
        DESTINO_read : OUT STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_fifo_w64_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_start_for_layer1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_start_for_consumer_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        input1 : OUT STD_LOGIC_VECTOR (63 downto 0);
        input2 : OUT STD_LOGIC_VECTOR (63 downto 0);
        output_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        MM : OUT STD_LOGIC_VECTOR (31 downto 0);
        NN : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component MVM_opcion7_super_mejorada_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    control_s_axi_U : component MVM_opcion7_super_mejorada_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        input1 => input1,
        input2 => input2,
        output_r => output_r,
        MM => MM,
        NN => NN,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_m_axi_U : component MVM_opcion7_super_mejorada_gmem_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 64,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => producer3_U0_m_axi_gmem_ARVALID,
        I_ARREADY => gmem_ARREADY,
        I_ARADDR => producer3_U0_m_axi_gmem_ARADDR,
        I_ARID => producer3_U0_m_axi_gmem_ARID,
        I_ARLEN => producer3_U0_m_axi_gmem_ARLEN,
        I_ARSIZE => producer3_U0_m_axi_gmem_ARSIZE,
        I_ARLOCK => producer3_U0_m_axi_gmem_ARLOCK,
        I_ARCACHE => producer3_U0_m_axi_gmem_ARCACHE,
        I_ARQOS => producer3_U0_m_axi_gmem_ARQOS,
        I_ARPROT => producer3_U0_m_axi_gmem_ARPROT,
        I_ARUSER => producer3_U0_m_axi_gmem_ARUSER,
        I_ARBURST => producer3_U0_m_axi_gmem_ARBURST,
        I_ARREGION => producer3_U0_m_axi_gmem_ARREGION,
        I_RVALID => gmem_RVALID,
        I_RREADY => producer3_U0_m_axi_gmem_RREADY,
        I_RDATA => gmem_RDATA,
        I_RID => gmem_RID,
        I_RUSER => gmem_RUSER,
        I_RRESP => gmem_RRESP,
        I_RLAST => gmem_RLAST,
        I_AWVALID => consumer_U0_m_axi_gmem_AWVALID,
        I_AWREADY => gmem_AWREADY,
        I_AWADDR => consumer_U0_m_axi_gmem_AWADDR,
        I_AWID => consumer_U0_m_axi_gmem_AWID,
        I_AWLEN => consumer_U0_m_axi_gmem_AWLEN,
        I_AWSIZE => consumer_U0_m_axi_gmem_AWSIZE,
        I_AWLOCK => consumer_U0_m_axi_gmem_AWLOCK,
        I_AWCACHE => consumer_U0_m_axi_gmem_AWCACHE,
        I_AWQOS => consumer_U0_m_axi_gmem_AWQOS,
        I_AWPROT => consumer_U0_m_axi_gmem_AWPROT,
        I_AWUSER => consumer_U0_m_axi_gmem_AWUSER,
        I_AWBURST => consumer_U0_m_axi_gmem_AWBURST,
        I_AWREGION => consumer_U0_m_axi_gmem_AWREGION,
        I_WVALID => consumer_U0_m_axi_gmem_WVALID,
        I_WREADY => gmem_WREADY,
        I_WDATA => consumer_U0_m_axi_gmem_WDATA,
        I_WID => consumer_U0_m_axi_gmem_WID,
        I_WUSER => consumer_U0_m_axi_gmem_WUSER,
        I_WLAST => consumer_U0_m_axi_gmem_WLAST,
        I_WSTRB => consumer_U0_m_axi_gmem_WSTRB,
        I_BVALID => gmem_BVALID,
        I_BREADY => consumer_U0_m_axi_gmem_BREADY,
        I_BRESP => gmem_BRESP,
        I_BID => gmem_BID,
        I_BUSER => gmem_BUSER);

    producer3_U0 : component MVM_opcion7_super_mejorada_producer3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => producer3_U0_ap_start,
        start_full_n => producer3_U0_start_full_n,
        ap_done => producer3_U0_ap_done,
        ap_continue => producer3_U0_ap_continue,
        ap_idle => producer3_U0_ap_idle,
        ap_ready => producer3_U0_ap_ready,
        start_out => producer3_U0_start_out,
        start_write => producer3_U0_start_write,
        aa_din => producer3_U0_aa_din,
        aa_full_n => a_full_n,
        aa_write => producer3_U0_aa_write,
        bb1_din => producer3_U0_bb1_din,
        bb1_full_n => b1_full_n,
        bb1_write => producer3_U0_bb1_write,
        m_axi_gmem_AWVALID => producer3_U0_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => ap_const_logic_0,
        m_axi_gmem_AWADDR => producer3_U0_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => producer3_U0_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => producer3_U0_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => producer3_U0_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => producer3_U0_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => producer3_U0_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => producer3_U0_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => producer3_U0_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => producer3_U0_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => producer3_U0_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => producer3_U0_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => producer3_U0_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => ap_const_logic_0,
        m_axi_gmem_WDATA => producer3_U0_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => producer3_U0_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => producer3_U0_m_axi_gmem_WLAST,
        m_axi_gmem_WID => producer3_U0_m_axi_gmem_WID,
        m_axi_gmem_WUSER => producer3_U0_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => producer3_U0_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => producer3_U0_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => producer3_U0_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => producer3_U0_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => producer3_U0_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => producer3_U0_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => producer3_U0_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => producer3_U0_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => producer3_U0_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => producer3_U0_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => producer3_U0_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => producer3_U0_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => producer3_U0_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => gmem_RLAST,
        m_axi_gmem_RID => gmem_RID,
        m_axi_gmem_RUSER => gmem_RUSER,
        m_axi_gmem_RRESP => gmem_RRESP,
        m_axi_gmem_BVALID => ap_const_logic_0,
        m_axi_gmem_BREADY => producer3_U0_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        activacion => input1,
        weight => input2,
        DESTINO => MM,
        ORIGEN => NN,
        output_r => output_r,
        DESTINO_out_din => producer3_U0_DESTINO_out_din,
        DESTINO_out_full_n => MM_c_full_n,
        DESTINO_out_write => producer3_U0_DESTINO_out_write,
        ORIGEN_out_din => producer3_U0_ORIGEN_out_din,
        ORIGEN_out_full_n => NN_c_full_n,
        ORIGEN_out_write => producer3_U0_ORIGEN_out_write,
        output_out_din => producer3_U0_output_out_din,
        output_out_full_n => output_c_full_n,
        output_out_write => producer3_U0_output_out_write);

    layer1_U0 : component MVM_opcion7_super_mejorada_layer1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => layer1_U0_ap_start,
        ap_done => layer1_U0_ap_done,
        ap_continue => layer1_U0_ap_continue,
        ap_idle => layer1_U0_ap_idle,
        ap_ready => layer1_U0_ap_ready,
        aa_dout => a_dout,
        aa_empty_n => a_empty_n,
        aa_read => layer1_U0_aa_read,
        bb1_dout => b1_dout,
        bb1_empty_n => b1_empty_n,
        bb1_read => layer1_U0_bb1_read,
        ss_din => layer1_U0_ss_din,
        ss_full_n => layer1_layer2_full_n,
        ss_write => layer1_U0_ss_write,
        DESTINO_dout => MM_c_dout,
        DESTINO_empty_n => MM_c_empty_n,
        DESTINO_read => layer1_U0_DESTINO_read,
        ORIGEN_dout => NN_c_dout,
        ORIGEN_empty_n => NN_c_empty_n,
        ORIGEN_read => layer1_U0_ORIGEN_read,
        DESTINO_out_din => layer1_U0_DESTINO_out_din,
        DESTINO_out_full_n => MM_c9_full_n,
        DESTINO_out_write => layer1_U0_DESTINO_out_write);

    consumer_U0 : component MVM_opcion7_super_mejorada_consumer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => consumer_U0_ap_start,
        ap_done => consumer_U0_ap_done,
        ap_continue => consumer_U0_ap_continue,
        ap_idle => consumer_U0_ap_idle,
        ap_ready => consumer_U0_ap_ready,
        ss_dout => layer1_layer2_dout,
        ss_empty_n => layer1_layer2_empty_n,
        ss_read => consumer_U0_ss_read,
        m_axi_gmem_AWVALID => consumer_U0_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => consumer_U0_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => consumer_U0_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => consumer_U0_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => consumer_U0_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => consumer_U0_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => consumer_U0_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => consumer_U0_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => consumer_U0_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => consumer_U0_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => consumer_U0_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => consumer_U0_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => consumer_U0_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => consumer_U0_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => consumer_U0_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => consumer_U0_m_axi_gmem_WLAST,
        m_axi_gmem_WID => consumer_U0_m_axi_gmem_WID,
        m_axi_gmem_WUSER => consumer_U0_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => consumer_U0_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => ap_const_logic_0,
        m_axi_gmem_ARADDR => consumer_U0_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => consumer_U0_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => consumer_U0_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => consumer_U0_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => consumer_U0_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => consumer_U0_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => consumer_U0_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => consumer_U0_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => consumer_U0_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => consumer_U0_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => consumer_U0_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => ap_const_logic_0,
        m_axi_gmem_RREADY => consumer_U0_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => ap_const_lv32_0,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => consumer_U0_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => gmem_BRESP,
        m_axi_gmem_BID => gmem_BID,
        m_axi_gmem_BUSER => gmem_BUSER,
        activacion_dout => output_c_dout,
        activacion_empty_n => output_c_empty_n,
        activacion_read => consumer_U0_activacion_read,
        DESTINO_dout => MM_c9_dout,
        DESTINO_empty_n => MM_c9_empty_n,
        DESTINO_read => consumer_U0_DESTINO_read);

    a_U : component MVM_opcion7_super_mejorada_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => producer3_U0_aa_din,
        if_full_n => a_full_n,
        if_write => producer3_U0_aa_write,
        if_dout => a_dout,
        if_empty_n => a_empty_n,
        if_read => layer1_U0_aa_read);

    b1_U : component MVM_opcion7_super_mejorada_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => producer3_U0_bb1_din,
        if_full_n => b1_full_n,
        if_write => producer3_U0_bb1_write,
        if_dout => b1_dout,
        if_empty_n => b1_empty_n,
        if_read => layer1_U0_bb1_read);

    MM_c_U : component MVM_opcion7_super_mejorada_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => producer3_U0_DESTINO_out_din,
        if_full_n => MM_c_full_n,
        if_write => producer3_U0_DESTINO_out_write,
        if_dout => MM_c_dout,
        if_empty_n => MM_c_empty_n,
        if_read => layer1_U0_DESTINO_read);

    NN_c_U : component MVM_opcion7_super_mejorada_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => producer3_U0_ORIGEN_out_din,
        if_full_n => NN_c_full_n,
        if_write => producer3_U0_ORIGEN_out_write,
        if_dout => NN_c_dout,
        if_empty_n => NN_c_empty_n,
        if_read => layer1_U0_ORIGEN_read);

    output_c_U : component MVM_opcion7_super_mejorada_fifo_w64_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => producer3_U0_output_out_din,
        if_full_n => output_c_full_n,
        if_write => producer3_U0_output_out_write,
        if_dout => output_c_dout,
        if_empty_n => output_c_empty_n,
        if_read => consumer_U0_activacion_read);

    layer1_layer2_U : component MVM_opcion7_super_mejorada_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => layer1_U0_ss_din,
        if_full_n => layer1_layer2_full_n,
        if_write => layer1_U0_ss_write,
        if_dout => layer1_layer2_dout,
        if_empty_n => layer1_layer2_empty_n,
        if_read => consumer_U0_ss_read);

    MM_c9_U : component MVM_opcion7_super_mejorada_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => layer1_U0_DESTINO_out_din,
        if_full_n => MM_c9_full_n,
        if_write => layer1_U0_DESTINO_out_write,
        if_dout => MM_c9_dout,
        if_empty_n => MM_c9_empty_n,
        if_read => consumer_U0_DESTINO_read);

    start_for_layer1_U0_U : component MVM_opcion7_super_mejorada_start_for_layer1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_layer1_U0_din,
        if_full_n => start_for_layer1_U0_full_n,
        if_write => producer3_U0_start_write,
        if_dout => start_for_layer1_U0_dout,
        if_empty_n => start_for_layer1_U0_empty_n,
        if_read => layer1_U0_ap_ready);

    start_for_consumer_U0_U : component MVM_opcion7_super_mejorada_start_for_consumer_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_consumer_U0_din,
        if_full_n => start_for_consumer_U0_full_n,
        if_write => producer3_U0_start_write,
        if_dout => start_for_consumer_U0_dout,
        if_empty_n => start_for_consumer_U0_empty_n,
        if_read => consumer_U0_ap_ready);




    ap_done <= consumer_U0_ap_done;
    ap_idle <= (producer3_U0_ap_idle and layer1_U0_ap_idle and consumer_U0_ap_idle);
    ap_ready <= producer3_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= consumer_U0_ap_done;
    ap_sync_ready <= producer3_U0_ap_ready;
    consumer_U0_ap_continue <= ap_const_logic_1;
    consumer_U0_ap_start <= start_for_consumer_U0_empty_n;
    consumer_U0_start_full_n <= ap_const_logic_1;
    consumer_U0_start_write <= ap_const_logic_0;
    layer1_U0_ap_continue <= ap_const_logic_1;
    layer1_U0_ap_start <= start_for_layer1_U0_empty_n;
    layer1_U0_start_full_n <= ap_const_logic_1;
    layer1_U0_start_write <= ap_const_logic_0;
    producer3_U0_ap_continue <= ap_const_logic_1;
    producer3_U0_ap_start <= ap_start;
    producer3_U0_start_full_n <= (start_for_layer1_U0_full_n and start_for_consumer_U0_full_n);
    start_for_consumer_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_layer1_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
